name: snap_fit
description: "A new Flutter project."

publish_to: "none"

version: 1.0.1+1

environment:
  sdk: ^3.5.4

dependencies:
  flutter:
    sdk: flutter
  flutter_localizations:
    sdk: flutter
  cupertino_icons: ^1.0.8
  hive_flutter: ^1.1.0
  window_manager: ^0.4.3
  flutter_bloc: ^8.1.6
  image: ^4.3.0
  desktop_drop: ^0.5.0
  dotted_border: ^2.1.0
  mime: ^2.0.0
  file_picker: ^8.1.3
  path: ^1.9.0
  path_provider: ^2.1.5
  rxdart: ^0.28.0

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^5.0.0

flutter:
  uses-material-design: true
